### ISSUE TITLE
Files Hardwarevariante V2

### ISSUE THREAD

**Issue by GatoPharaoh** [mgerhard74/amis_smartmeter_reader#1]
Hi!

vielen Dank für dieses großartige Projekt. Stehen die Files für die auf der Webseite erwähnte `Hardwarevariante (V2; ab 2023)` ebenfalls zur Verfügung? Ich konnte sie nicht finden.

lg

**Comment by mgerhard74** [comment]
Guten Tag,
ich möchte bewusst nur die Hardwarevariante V1 zur Verfügung stellen. Diese eignet sich m.E. besser zum Nachbau, flashen ist durch die dreipolige Stiftleiste einfacher.
Ich habe noch ein paar V2 über, bitte schreibe auf die EMail Adresse, die auf meine Website angegeben ist.
lg
