### ISSUE TITLE
MQTT connection is not working

### ISSUE THREAD

**Issue by superwolfi82** [mgerhard74/amis_smartmeter_reader#6]
Hallo Zusammen

Ich habe zwei AMIS Reader mit der Version 1.2.7 und habe das problem, dass via MQTT keine Daten an Homeassistant (mosquitto) gesendet werden, die Abfrage von homeassistant via Rest funktioniert ohne probleme.

![image](https://github.com/user-attachments/assets/672f90e9-0f88-44ed-b0e0-4eccb4ae317b)

vom Amis-reader scheint die connection  successful established

![image](https://github.com/user-attachments/assets/2e77a734-ba67-4bea-a0fc-1901b0686f48)

auch auf Mesquite seite im debug sehe ich die connection "MQTT ping" messages  aber leider keine publish messages

![image](https://github.com/user-attachments/assets/6b44e64a-ef8f-4ca4-86d9-1c165458862f)

2024-08-13 12:45:32: Received PINGREQ from Amis-normalstrom
2024-08-13 12:45:32: Sending PINGRESP to Amis-normalstrom
2024-08-13 12:45:35: Received PINGREQ from Amis-warm
2024-08-13 12:45:35: Sending PINGRESP to Amis-warm

auf dem broker, hängen ca. 15-20 andere mqtt devises dran (shelly, tasmotta, die ohne Probleme funktionieren)

Note die zeitstempeln passen nicht 100% zusammen ... 

ich habe auch den post https://github.com/mgerhard74/amis_smartmeter_reader/issues/4 von 
@tiotuba @csc-solution gesehen und habe es mit deren Parametern probiert .. auch kein erfolg

**Comment by superwolfi82** [comment]
kleines update -- ich lasse das ganze drinnen, es scheint so als braucht der mqtt stream ca 15 min is daten gesendet werden.. 

![image](https://github.com/user-attachments/assets/e2197d68-2f28-48d1-a293-230b53740c7b)

**Comment by maxus-git** [comment]
Hallo superwolfi82,

dreh deinen "MQTT Keep Alive" von 900 mal auf 1 Sekunde ;-)
(900 / 60 = 15min)

LG Markus

**Comment by mgerhard74** [comment]
Danke Markus, 
wollte ich auch gerade antworten. lg Gerhard

**Comment by superwolfi82** [comment]
@maxus-git  @mgerhard74   Danke .. :-) 

ist ein bisschen verwirrend wenn das MQTT Keep Alive als sende intervall doppelt verwendet wird  (ja es steht im kleingedruckten...)

gibt es eine Möglichkeit bei jedem signal vom stromzähler dies übertragen zu bekommen  ?

**Comment by mgerhard74** [comment]
Ja, stelle 1 sec. ein.
lg Gerhard

**Comment by superwolfi82** [comment]
danke!

**Comment by maxus-git** [comment]
@mgerhard74
Wäre eine Idee für ein künftiges Update, das Publish-Intervall vom Keep Alive zu trennen.

**Comment by mgerhard74** [comment]
Webinterface angepasst: Feld auf "MQTT Publish-Intervall/Keep Alive" geändert.
